server:
  port: 8467
  bookshelf-log:
    interval: 10
user:
  client:
    url: http://localhost:8466/shelfUser/
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bookshelf
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    contexts: prod
    #contexts: test
    dropFirst: false
    parameters:
      bookshelf-log:
        interval: ${server.bookshelf-log.interval}